### PR TITLE
updating support info in LICENSE and README

### PR DESCRIPTION
**Pull request by paxtonhare**

### CODE REVIEW

**Comment by paxtonhare** [comment]
I wasn't sure if we were explicitly stating that we are supported.

**Comment by paxtonhare** [comment]
@popzip thoughts?

**Comment by popzip** [comment]
yes thats been on my plate to confirm wording this week. still planning to get to it. I thought it was lower down in the story queue so had time to provide the full text. can you wait on this?

**Comment by paxtonhare** [comment]
@popzip I can wait. I was just knocking off an easy one while tests ran.

**Pull request merged**
